import os
from utils.Graph import Graph

print()
graph = Graph('./assets/agm_tiny.net')
print()
print(f"Qtd de vertices: {graph.qtdVertices()}")
print(f"Qtd de arestas: {graph.qtdArestas()}")
print(f"Grau do vertice 1: {graph.grau(1)}")
print(f"Grau do vertice 2: {graph.grau(2)}")
print(f"Rotulo do vertice 1: {graph.rotulo(1)}")
print(f"Vizinhos do vertice 1: {graph.vizinhos(1)}")
print(f"Há aresta entre 1 e 2? {graph.haAresta(1, 2)}")
print(f"Há aresta entre 1 e 5? {graph.haAresta(1, 5)}")
print(f"Qual o peso de 1 e 3? {graph.peso(1, 3)}")
print(f"Qual o peso de 1 e 5? {graph.peso(1, 5)}")

print()

graph = Graph('./assets/fln_pequena.net')
print(f"Qtd de vertices: {graph.qtdVertices()}")
print(f"Qtd de arestas: {graph.qtdArestas()}")
print(f"Grau do vertice 1: {graph.grau(1)}")
print(f"Grau do vertice 2: {graph.grau(2)}")
print(f"Rotulo do vertice 1: {graph.rotulo(1)}")
print(f"Vizinhos do vertice 1: {graph.vizinhos(1)}")
print(f"Há aresta entre 1 e 2? {graph.haAresta(1, 2)}")
print(f"Há aresta entre 1 e 5? {graph.haAresta(1, 5)}")
print(f"Qual o peso de 1 e 3? {graph.peso(1, 3)}")
print(f"Qual o peso de 1 e 5? {graph.peso(1, 5)}")
